# Generated by Django 3.2.16 on 2022-11-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('idU', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, null=True)),
                ('apellidos', models.CharField(max_length=50, null=True)),
                ('edad', models.PositiveIntegerField(null=True)),
                ('usuario', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('esAdmin', models.BooleanField()),
                ('fechaCreacion', models.DateField()),
            ],
        ),
    ]
