# Generated by Django 3.2.16 on 2022-12-31 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_usuario_correo'),
    ]

    operations = [
        migrations.CreateModel(
            name='listaVerificacion',
            fields=[
                ('idLV', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreLV', models.CharField(max_length=200)),
                ('fechaCreacion', models.DateField()),
                ('requisitoCalidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('idP', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProd', models.CharField(max_length=40)),
                ('versionProd', models.CharField(max_length=40)),
                ('fechaCreacion', models.DateField()),
                ('fechaLimite', models.DateField()),
                ('centroOrigen', models.CharField(max_length=700)),
                ('productoRevisado', models.BooleanField()),
                ('iteracion', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre',
            new_name='nombreUser',
        ),
        migrations.CreateModel(
            name='preguntas',
            fields=[
                ('idp', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preguta', models.CharField(max_length=2000)),
                ('respuesta', models.CharField(max_length=50)),
                ('idLV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.listaverificacion')),
            ],
        ),
    ]
