# Generated by Django 3.2.16 on 2023-01-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0005_pul'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntas',
            name='No',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preguntas',
            name='tipo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='observacion',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='respuesta',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
