# Generated by Django 3.2.16 on 2023-01-11 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0006_auto_20230107_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='UPL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idLV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.listaverificacion')),
                ('idP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.producto')),
                ('idU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.usuario')),
            ],
        ),
    ]
