# Generated by Django 3.2.16 on 2023-01-15 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0008_delete_upl'),
    ]

    operations = [
        migrations.CreateModel(
            name='preguntasU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No', models.IntegerField()),
                ('preguta', models.CharField(max_length=2000)),
                ('respuesta', models.CharField(max_length=50, null=True)),
                ('observacion', models.CharField(max_length=1000, null=True)),
                ('tipo', models.CharField(max_length=200)),
                ('idLV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.listaverificacion')),
                ('idU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.usuario')),
            ],
        ),
    ]
