# Generated by Django 3.2.16 on 2023-01-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0009_preguntasu'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntasu',
            name='modif',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
