# Generated by Django 3.2.16 on 2023-01-15 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0010_preguntasu_modif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntasu',
            name='tipo',
        ),
    ]
